import type { SpriteType } from '../core/model';

export interface BestiaryEntry {
  name: string;
  kind: 'creature' | 'object';
  fact: string;
}

/** Field-guide entries for the "Sổ Tay Sinh Vật" album — one per sprite type. */
export const BESTIARY: Record<Exclude<SpriteType, 'seal'>, BestiaryEntry> = {
  // Sinh vật
  cat: { name: 'Mèo tam thể', kind: 'creature', fact: 'Mèo dành khoảng hai phần ba cuộc đời để ngủ — nên chúng rất giỏi nằm im ẩn mình.' },
  dog: { name: 'Cún con', kind: 'creature', fact: 'Khứu giác của chó nhạy hơn con người hàng chục nghìn lần.' },
  owl: { name: 'Cú mèo', kind: 'creature', fact: 'Cú có thể xoay đầu khoảng 270 độ vì mắt chúng không đảo được trong hốc mắt.' },
  dove: { name: 'Chim bồ câu', kind: 'creature', fact: 'Bồ câu có thể tìm đường về tổ từ nơi cách xa hàng trăm cây số.' },
  butterfly: { name: 'Bướm ngọc', kind: 'creature', fact: 'Bướm "nếm" vị bằng chân — chúng đậu lên lá để biết lá có ăn được không.' },
  squirrel: { name: 'Sóc', kind: 'creature', fact: 'Sóc hay quên chỗ giấu hạt, và nhờ vậy vô tình trồng thêm rất nhiều cây.' },
  turtle: { name: 'Rùa', kind: 'creature', fact: 'Mai rùa gắn liền với xương sống, nên rùa không bao giờ "chui ra" khỏi mai được.' },
  gecko: { name: 'Thạch sùng', kind: 'creature', fact: 'Ở Singapore thạch sùng được gọi là "cicak" — đọc gần giống tiếng kêu chắc chắc của chúng.' },
  chameleon: { name: 'Tắc kè hoa', kind: 'creature', fact: 'Tắc kè hoa đổi màu chủ yếu để "nói chuyện" và điều chỉnh thân nhiệt, không chỉ để ngụy trang.' },
  frog: { name: 'Ếch', kind: 'creature', fact: 'Ếch hầu như không uống nước — chúng hấp thụ nước qua da.' },
  snail: { name: 'Ốc sên', kind: 'creature', fact: 'Lưỡi ốc sên có hàng nghìn chiếc răng siêu nhỏ xếp thành hàng.' },
  ladybug: { name: 'Bọ rùa', kind: 'creature', fact: 'Một con bọ rùa có thể ăn hàng nghìn con rệp trong đời — người làm vườn rất quý chúng.' },
  mouse: { name: 'Chuột nhắt', kind: 'creature', fact: 'Chuột nhắt có thể lách qua khe hở chỉ cỡ một chiếc bút chì.' },
  koi: { name: 'Cá koi', kind: 'creature', fact: 'Được chăm sóc tốt, cá koi có thể sống vài chục năm.' },
  crab: { name: 'Cua', kind: 'creature', fact: 'Cua bò ngang vì các khớp chân của chúng gập sang hai bên.' },
  otter: { name: 'Rái cá lông mượt', kind: 'creature', fact: 'Rái cá lông mượt từng gần như biến mất khỏi Singapore, nay đã quay về sống ngay giữa sông và vịnh thành phố.' },
  kingfisher: { name: 'Chim bói cá', kind: 'creature', fact: 'Bói cá khoang cổ phổ biến ở Singapore không chỉ ăn cá mà còn săn cả cua và côn trùng.' },
  bat: { name: 'Dơi quả', kind: 'creature', fact: 'Dơi là loài thú duy nhất thật sự biết bay.' },
  monkey: { name: 'Khỉ đuôi dài', kind: 'creature', fact: 'Ở Singapore, cho khỉ hoang ăn là vi phạm pháp luật — để chúng không phụ thuộc vào con người.' },
  moth: { name: 'Bướm đêm', kind: 'creature', fact: 'Nhiều loài bướm đêm có cánh giống hệt lá khô hay vỏ cây để trốn chim săn mồi.' },
  dragonfly: { name: 'Chuồn chuồn', kind: 'creature', fact: 'Chuồn chuồn có thể bay lùi và lơ lửng tại chỗ như trực thăng.' },
  spider: { name: 'Nhện', kind: 'creature', fact: 'Xét theo cùng trọng lượng, tơ nhện bền chẳng kém gì thép.' },
  heron: { name: 'Diệc xám', kind: 'creature', fact: 'Diệc có thể đứng bất động rất lâu bên mép nước để rình cá.' },
  hornbill: { name: 'Chim mỏ sừng', kind: 'creature', fact: 'Chim mỏ sừng Phương Đông từng biến mất khỏi Singapore và đã tự quay về đảo Pulau Ubin vào những năm 1990.' },
  pangolin: { name: 'Tê tê Sunda', kind: 'creature', fact: 'Tê tê là loài thú có vảy sừng; khi sợ hãi chúng cuộn tròn như một quả bóng.' },
  'monitor-lizard': { name: 'Kỳ đà nước', kind: 'creature', fact: 'Kỳ đà nước là loài bò sát lớn thường bơi dọc kênh rạch và sông ở Singapore.' },
  jellyfish: { name: 'Sứa', kind: 'creature', fact: 'Sứa không có não, không có tim, và phần lớn cơ thể là nước.' },
  seahorse: { name: 'Cá ngựa', kind: 'creature', fact: 'Ở loài cá ngựa, con đực mới là con mang trứng và sinh con.' },
  mantis: { name: 'Bọ ngựa', kind: 'creature', fact: 'Bọ ngựa có thể quay đầu gần như nửa vòng để dõi theo con mồi.' },
  firefly: { name: 'Đom đóm', kind: 'creature', fact: 'Đom đóm nhấp nháy để tìm bạn đời — mỗi loài có một "mật mã" ánh sáng riêng.' },
  civet: { name: 'Cầy vòi hương', kind: 'creature', fact: 'Cầy vòi hương (musang) sống về đêm, hay trú trên mái nhà cũ và rất mê trái cây chín.' },
  sunbird: { name: 'Chim hút mật', kind: 'creature', fact: 'Chim hút mật lưng ô liu thường làm tổ treo lủng lẳng ngay ngoài ban công nhà dân Singapore.' },
  'slow-loris': { name: 'Culi Sunda', kind: 'creature', fact: 'Culi là loài linh trưởng sống về đêm với đôi mắt to tròn giúp nhìn rõ trong bóng tối.' },
  colugo: { name: 'Chồn bay Sunda', kind: 'creature', fact: 'Chồn bay có thể lượn xa hàng chục mét giữa các thân cây nhờ lớp màng da như chiếc áo choàng.' },
  'stick-insect': { name: 'Bọ que', kind: 'creature', fact: 'Bọ que ngụy trang giỏi đến mức còn đung đưa theo gió cho giống một cành cây thật.' },
  saola: { name: 'Sao la', kind: 'creature', fact: 'Được mệnh danh là "Kỳ lân châu Á", sao la là loài thú quý hiếm chỉ sinh sống tại vùng rừng già dãy Trường Sơn.' },
  'water-buffalo': { name: 'Trâu nước', kind: 'creature', fact: 'Con trâu là đầu cơ nghiệp — loài vật hiền lành gắn liền với nền văn minh lúa nước ngàn đời của người Việt.' },
  'golden-turtle': { name: 'Rùa vàng Kim Quy', kind: 'creature', fact: 'Thần Kim Quy gắn liền với huyền tích xây thành Cổ Loa và thanh gươm Thuận Thiên trả lại nơi hồ Gươm.' },
  'dong-tao-chicken': { name: 'Gà Đông Tảo', kind: 'creature', fact: 'Giống gà tiến vua trứ danh của Hưng Yên với đôi chân to xù xì như vảy rồng và vóc dáng dũng mãnh.' },
  'hmong-dog': { name: 'Chó H\'Mông cộc đuôi', kind: 'creature', fact: 'Quốc khuyển vùng cao Tây Bắc với chiếc đuôi cộc tròn ngộ nghĩnh, nổi tiếng dũng cảm và tuyệt đối trung thành.' },
  langur: { name: 'Voọc mông trắng', kind: 'creature', fact: 'Loài linh trưởng đặc hữu cực kỳ quý hiếm chỉ sinh sống tại vùng núi đá vôi miền Bắc Việt Nam.' },
  'highland-elephant': { name: 'Voi Bản Đôn', kind: 'creature', fact: 'Biểu tượng huyền thoại của buôn làng Tây Nguyên, gắn bó sâu sắc với đời sống văn hóa đồng bào nơi đây.' },
  mudskipper: { name: 'Cá thòi lòi', kind: 'creature', fact: 'Loài cá kỳ lạ của rừng đước Cà Mau có đôi mắt lồi, biết thở trên cạn, nhảy nhót và leo trèo thoăn thoắt trên rễ cây.' },
  'ca-mau-crab': { name: 'Cua Cà Mau', kind: 'creature', fact: 'Cua biển Năm Căn Cà Mau nổi danh với đôi càng to kềnh, thịt chắc ngọt đậm đà nhờ phù sa đất mũi.' },
  'phu-quoc-dog': { name: 'Chó xoáy Phú Quốc', kind: 'creature', fact: 'Giống chó săn đảo ngọc bản địa thông minh bậc nhất, có màng chân bơi lội và dải xoáy lông hình lưỡi kiếm trên lưng.' },
  dugong: { name: 'Bò biển Dugong', kind: 'creature', fact: 'Được mệnh danh là "nàng tiên cá" của đại dương, loài thú biển hiền hòa này tìm về gặm cỏ biển tại vùng biển Phú Quốc.' },
  // Đồ vật
  key: { name: 'Chìa khóa cổ', kind: 'object', fact: 'Chìa khóa cổ có phần răng được rèn thủ công, khớp với đúng một ổ khóa.' },
  compass: { name: 'La bàn', kind: 'object', fact: 'Kim la bàn luôn chỉ theo từ trường Trái Đất, dẫn đường cho thủy thủ suốt nhiều thế kỷ.' },
  letter: { name: 'Thư niêm sáp', kind: 'object', fact: 'Con dấu sáp từng dùng để niêm phong thư và chứng minh ai là người gửi.' },
  'pocket-watch': { name: 'Đồng hồ quả quýt', kind: 'object', fact: 'Đồng hồ bỏ túi rất phổ biến trước khi đồng hồ đeo tay thịnh hành vào đầu thế kỷ 20.' },
  quill: { name: 'Bút lông ngỗng', kind: 'object', fact: 'Bút lông ngỗng là cây bút viết phổ biến ở châu Âu suốt hơn một nghìn năm.' },
  teacup: { name: 'Tách trà Peranakan', kind: 'object', fact: 'Đồ sứ Peranakan (Nyonya ware) nổi bật với sắc hồng, xanh ngọc và họa tiết phượng hoàng.' },
  'coin-pouch': { name: 'Túi tiền xu', kind: 'object', fact: 'Thời thuộc địa, người Singapore tiêu "đô la eo biển" (Straits dollar).' },
  spyglass: { name: 'Ống nhòm viễn vọng', kind: 'object', fact: 'Kính viễn vọng khúc xạ ra đời ở Hà Lan vào đầu thế kỷ 17.' },
  vase: { name: 'Bình gốm men lam', kind: 'object', fact: 'Gốm men lam được vẽ hoa văn bằng màu cobalt rồi mới tráng men và nung.' },
  scroll: { name: 'Cuộn kinh cổ', kind: 'object', fact: 'Kinh sách thời xưa thường được chép tay trên những cuộn giấy dài.' },
  'magnifying-glass': { name: 'Kính lúp', kind: 'object', fact: 'Kính lúp trở thành "biểu tượng" của nghề thám tử nhờ những câu chuyện về Sherlock Holmes.' },
  'paper-crane': { name: 'Hạc giấy', kind: 'object', fact: 'Theo truyền thuyết Nhật Bản, ai gấp đủ 1.000 con hạc giấy sẽ được một điều ước.' },
  'paper-boat': { name: 'Thuyền giấy', kind: 'object', fact: 'Thuyền bumboat trên sông Singapore xưa được vẽ đôi mắt ở mũi để "nhìn đường" tránh hiểm nguy.' },
  durian: { name: 'Sầu riêng', kind: 'object', fact: 'Sầu riêng không được mang lên tàu điện MRT vì mùi quá nồng — còn nhà hát Esplanade thì có biệt danh "quả sầu riêng".' },
  'fortune-cat': { name: 'Mèo thần tài', kind: 'object', fact: 'Người ta tin mèo thần tài giơ tay phải để gọi tài lộc, giơ tay trái để mời khách.' },
  'red-envelope': { name: 'Bao lì xì', kind: 'object', fact: 'Bao lì xì (ang pow) màu đỏ tượng trưng cho may mắn, thường được tặng dịp Tết Nguyên Đán.' },
  tiffin: { name: 'Cà mèn tingkat', kind: 'object', fact: 'Cà mèn tingkat nhiều tầng từng là "hộp cơm" quen thuộc của các gia đình Peranakan.' },
  satay: { name: 'Xiên satay', kind: 'object', fact: 'Mỗi tối, một đoạn phố cạnh chợ Lau Pa Sat được đóng lại để thành "Phố Satay".' },
  kite: { name: 'Diều wau bulan', kind: 'object', fact: 'Wau bulan — diều "trăng khuyết" — là loại diều truyền thống nổi tiếng của người Mã Lai.' },
  'vintage-camera': { name: 'Máy ảnh cổ', kind: 'object', fact: 'Những chiếc máy ảnh đầu tiên cần tới vài phút phơi sáng để chụp một tấm hình.' },
  hourglass: { name: 'Đồng hồ cát', kind: 'object', fact: 'Đồng hồ cát từng được dùng trên tàu biển để đo thời gian và ước tính tốc độ.' },
  deerstalker: { name: 'Mũ thám tử', kind: 'object', fact: 'Chiếc mũ hai lưỡi trai gắn liền với Sherlock Holmes nhờ các bức tranh minh họa truyện.' },
  'conical-hat': { name: 'Nón lá', kind: 'object', fact: 'Chiếc nón lá truyền thống đan từ lá cọ vừa che mưa nắng vừa là nét duyên dáng của người Việt Nam.' },
  lantern: { name: 'Đèn lồng Hội An', kind: 'object', fact: 'Đèn lồng phố Hội được làm từ khung tre và lụa tơ tằm, thắp sáng lung linh sông Hoài vào những đêm rằm.' },
  cyclo: { name: 'Xích lô', kind: 'object', fact: 'Xích lô là phương tiện giao thông ba bánh độc đáo, đưa du khách thong thả ngắm nhìn phố phường cổ kính.' },
  'water-puppet': { name: 'Chú Tễu rối nước', kind: 'object', fact: 'Nhân vật dẫn chuyện hóm hỉnh của nghệ thuật múa rối nước dân gian độc nhất vô nhị vùng đồng bằng Bắc Bộ.' },
  khen: { name: 'Khèn H\'Mông', kind: 'object', fact: 'Cây khèn trúc là linh hồn trong các lễ hội mùa xuân, gửi gắm tiếng lòng tha thiết của chàng trai miền sơn cước.' },
  'cham-statue': { name: 'Vũ nữ Apsara', kind: 'object', fact: 'Tượng sa thạch vũ nữ Apsara thể hiện điệu múa uyển chuyển, huyền bí trên các đền tháp Chăm pa ngàn năm.' },
  gong: { name: 'Cồng chiêng Tây Nguyên', kind: 'object', fact: 'Di sản văn hóa phi vật thể của nhân loại, âm vang cồng chiêng nối kết con người với thần linh và đại ngàn.' },
  'dragon-boat': { name: 'Thuyền rồng sông Hương', kind: 'object', fact: 'Thuyền rồng hoàng cung triều Nguyễn từng đưa vua ngự du nghe ca Huế trên dòng Hương giang thơ mộng.' },
  'dan-bau': { name: 'Đàn bầu', kind: 'object', fact: 'Cây đàn độc huyền cầm chỉ với một dây nhưng tạo nên thanh âm ngân vang trầm bổng rung động lòng người.' },
  'banh-mi': { name: 'Bánh mì Sài Gòn', kind: 'object', fact: 'Món ăn đường phố trứ danh của Việt Nam với vỏ bánh giòn rụm và nhân đậm đà, nức tiếng khắp năm châu.' },
  'coffee-phin': { name: 'Cà phê phin', kind: 'object', fact: 'Chiếc phin nhôm nhỏ từng giọt tí tách tạo nên phong cách thưởng thức cà phê chậm rãi đặc trưng của người Việt.' },
  sampan: { name: 'Xuồng ba lá', kind: 'object', fact: 'Con xuồng gỗ mộc chở hoa trái và nhịp sống tấp nập của người dân trên các dòng kênh rạch miền Tây.' },
  'dong-son-drum': { name: 'Trống đồng Đông Sơn', kind: 'object', fact: 'Bảo vật thời kỳ Văn Lang - Âu Lạc với hoa văn mặt trời tỏa tia và đàn chim Lạc bay.' },
  'pho-bowl': { name: 'Bát phở Thăng Long', kind: 'object', fact: 'Món quốc hồn quốc túy của ẩm thực Việt với nước dùng ninh xương thảo mộc thơm nức hành hoa.' },
  brocade: { name: 'Thổ cẩm Tây Bắc', kind: 'object', fact: 'Những tấm vải dệt hoa văn hình học rực rỡ mang bản sắc và tâm hồn của đồng bào vùng cao.' },
  'basket-boat': { name: 'Thuyền thúng nan', kind: 'object', fact: 'Chiếc thuyền tròn đan bằng nan tre trét chai độc đáo của ngư dân làng chài duyên hải miền Trung.' },
  'ao-dai': { name: 'Áo dài truyền thống', kind: 'object', fact: 'Trang phục truyền thống tôn vinh nét đẹp kín đáo, thanh tao và duyên dáng của người Việt Nam.' },
  't-rung': { name: 'Đàn T\'rưng Tây Nguyên', kind: 'object', fact: 'Nhạc cụ gõ làm từ những ống nứa tự nhiên phát ra âm thanh trong trẻo như tiếng suối ngàn reo ca.' },
  coconut: { name: 'Trái dừa Nam Bộ', kind: 'object', fact: 'Thức quả ngọt mát biểu trưng cho sự trù phú và thanh bình của miền sông nước đồng bằng sông Cửu Long.' },
};

export function isCreature(type?: SpriteType): boolean {
  return !!type && type !== 'seal' && BESTIARY[type].kind === 'creature';
}
