import type { SpriteType } from '../core/model';

export interface BestiaryEntry {
  name: string;
  kind: 'creature' | 'object';
  fact: string;
}

/** Field-guide entries for the "Sổ Tay Sinh Vật" album — one per sprite type. */
export const BESTIARY: Record<Exclude<SpriteType, 'seal'>, BestiaryEntry> = {
  // Sinh vật
  cat: { name: 'Mèo tam thể', kind: 'creature', fact: 'Mèo dành khoảng hai phần ba cuộc đời để ngủ — nên chúng rất giỏi nằm im ẩn mình.' },
  dog: { name: 'Cún con', kind: 'creature', fact: 'Khứu giác của chó nhạy hơn con người hàng chục nghìn lần.' },
  owl: { name: 'Cú mèo', kind: 'creature', fact: 'Cú có thể xoay đầu khoảng 270 độ vì mắt chúng không đảo được trong hốc mắt.' },
  dove: { name: 'Chim bồ câu', kind: 'creature', fact: 'Bồ câu có thể tìm đường về tổ từ nơi cách xa hàng trăm cây số.' },
  butterfly: { name: 'Bướm ngọc', kind: 'creature', fact: 'Bướm "nếm" vị bằng chân — chúng đậu lên lá để biết lá có ăn được không.' },
  squirrel: { name: 'Sóc', kind: 'creature', fact: 'Sóc hay quên chỗ giấu hạt, và nhờ vậy vô tình trồng thêm rất nhiều cây.' },
  turtle: { name: 'Rùa', kind: 'creature', fact: 'Mai rùa gắn liền với xương sống, nên rùa không bao giờ "chui ra" khỏi mai được.' },
  gecko: { name: 'Thạch sùng', kind: 'creature', fact: 'Ở Singapore thạch sùng được gọi là "cicak" — đọc gần giống tiếng kêu chắc chắc của chúng.' },
  chameleon: { name: 'Tắc kè hoa', kind: 'creature', fact: 'Tắc kè hoa đổi màu chủ yếu để "nói chuyện" và điều chỉnh thân nhiệt, không chỉ để ngụy trang.' },
  frog: { name: 'Ếch', kind: 'creature', fact: 'Ếch hầu như không uống nước — chúng hấp thụ nước qua da.' },
  snail: { name: 'Ốc sên', kind: 'creature', fact: 'Lưỡi ốc sên có hàng nghìn chiếc răng siêu nhỏ xếp thành hàng.' },
  ladybug: { name: 'Bọ rùa', kind: 'creature', fact: 'Một con bọ rùa có thể ăn hàng nghìn con rệp trong đời — người làm vườn rất quý chúng.' },
  mouse: { name: 'Chuột nhắt', kind: 'creature', fact: 'Chuột nhắt có thể lách qua khe hở chỉ cỡ một chiếc bút chì.' },
  koi: { name: 'Cá koi', kind: 'creature', fact: 'Được chăm sóc tốt, cá koi có thể sống vài chục năm.' },
  crab: { name: 'Cua', kind: 'creature', fact: 'Cua bò ngang vì các khớp chân của chúng gập sang hai bên.' },
  otter: { name: 'Rái cá lông mượt', kind: 'creature', fact: 'Rái cá lông mượt từng gần như biến mất khỏi Singapore, nay đã quay về sống ngay giữa sông và vịnh thành phố.' },
  kingfisher: { name: 'Chim bói cá', kind: 'creature', fact: 'Bói cá khoang cổ phổ biến ở Singapore không chỉ ăn cá mà còn săn cả cua và côn trùng.' },
  bat: { name: 'Dơi quả', kind: 'creature', fact: 'Dơi là loài thú duy nhất thật sự biết bay.' },
  monkey: { name: 'Khỉ đuôi dài', kind: 'creature', fact: 'Ở Singapore, cho khỉ hoang ăn là vi phạm pháp luật — để chúng không phụ thuộc vào con người.' },
  moth: { name: 'Bướm đêm', kind: 'creature', fact: 'Nhiều loài bướm đêm có cánh giống hệt lá khô hay vỏ cây để trốn chim săn mồi.' },
  dragonfly: { name: 'Chuồn chuồn', kind: 'creature', fact: 'Chuồn chuồn có thể bay lùi và lơ lửng tại chỗ như trực thăng.' },
  spider: { name: 'Nhện', kind: 'creature', fact: 'Xét theo cùng trọng lượng, tơ nhện bền chẳng kém gì thép.' },
  heron: { name: 'Diệc xám', kind: 'creature', fact: 'Diệc có thể đứng bất động rất lâu bên mép nước để rình cá.' },
  hornbill: { name: 'Chim mỏ sừng', kind: 'creature', fact: 'Chim mỏ sừng Phương Đông từng biến mất khỏi Singapore và đã tự quay về đảo Pulau Ubin vào những năm 1990.' },
  pangolin: { name: 'Tê tê Sunda', kind: 'creature', fact: 'Tê tê là loài thú có vảy sừng; khi sợ hãi chúng cuộn tròn như một quả bóng.' },
  'monitor-lizard': { name: 'Kỳ đà nước', kind: 'creature', fact: 'Kỳ đà nước là loài bò sát lớn thường bơi dọc kênh rạch và sông ở Singapore.' },
  jellyfish: { name: 'Sứa', kind: 'creature', fact: 'Sứa không có não, không có tim, và phần lớn cơ thể là nước.' },
  seahorse: { name: 'Cá ngựa', kind: 'creature', fact: 'Ở loài cá ngựa, con đực mới là con mang trứng và sinh con.' },
  mantis: { name: 'Bọ ngựa', kind: 'creature', fact: 'Bọ ngựa có thể quay đầu gần như nửa vòng để dõi theo con mồi.' },
  firefly: { name: 'Đom đóm', kind: 'creature', fact: 'Đom đóm nhấp nháy để tìm bạn đời — mỗi loài có một "mật mã" ánh sáng riêng.' },
  civet: { name: 'Cầy vòi hương', kind: 'creature', fact: 'Cầy vòi hương (musang) sống về đêm, hay trú trên mái nhà cũ và rất mê trái cây chín.' },
  sunbird: { name: 'Chim hút mật', kind: 'creature', fact: 'Chim hút mật lưng ô liu thường làm tổ treo lủng lẳng ngay ngoài ban công nhà dân Singapore.' },
  'slow-loris': { name: 'Culi Sunda', kind: 'creature', fact: 'Culi là loài linh trưởng sống về đêm với đôi mắt to tròn giúp nhìn rõ trong bóng tối.' },
  colugo: { name: 'Chồn bay Sunda', kind: 'creature', fact: 'Chồn bay có thể lượn xa hàng chục mét giữa các thân cây nhờ lớp màng da như chiếc áo choàng.' },
  'stick-insect': { name: 'Bọ que', kind: 'creature', fact: 'Bọ que ngụy trang giỏi đến mức còn đung đưa theo gió cho giống một cành cây thật.' },
  saola: { name: 'Sao la', kind: 'creature', fact: 'Được mệnh danh là "Kỳ lân châu Á", sao la là loài thú quý hiếm chỉ sinh sống tại vùng rừng già dãy Trường Sơn.' },
  'water-buffalo': { name: 'Trâu nước', kind: 'creature', fact: 'Con trâu là đầu cơ nghiệp — loài vật hiền lành gắn liền với nền văn minh lúa nước ngàn đời của người Việt.' },
  betta: { name: 'Cá xiêm', kind: 'creature', fact: 'Cá xiêm (pla kat) là "quốc ngư" của Thái Lan; cá đực xòe vây rực rỡ và tự xây tổ bọt để giữ trứng.' },
  crocodile: { name: 'Cá sấu Xiêm', kind: 'creature', fact: 'Cá sấu Xiêm từng sống khắp sông ngòi Thái Lan, nay còn rất ít ngoài tự nhiên và đang được bảo tồn.' },
  mudskipper: { name: 'Cá thòi lòi', kind: 'creature', fact: 'Cá thòi lòi thở được qua da và miệng, nên có thể "đi bộ" trên bùn bằng vây ngực khi nước rút.' },
  'giant-catfish': { name: 'Cá tra dầu', kind: 'creature', fact: 'Cá tra dầu sông Mê Kông là một trong những loài cá nước ngọt lớn nhất thế giới, có con nặng gần 300 kg.' },
  'river-prawn': { name: 'Tôm càng xanh', kind: 'creature', fact: 'Tôm càng xanh đực có đôi càng dài hơn cả thân; tôm sông nướng là đặc sản của cố đô Ayutthaya.' },
  stingray: { name: 'Cá đuối nước ngọt', kind: 'creature', fact: 'Cá đuối nước ngọt khổng lồ sống ở các sông lớn Thái Lan như sông Mae Klong; tính cả đuôi, có con dài hơn 4 mét.' },
  goldfish: { name: 'Cá vàng', kind: 'creature', fact: 'Người Hoa tin cá vàng mang lại tài lộc, vì chữ "cá" (鱼, yú) đọc giống chữ "dư" (余) trong dư dả.' },
  'flying-snake': { name: 'Rắn bay thiên đường', kind: 'creature', fact: 'Rắn bay thiên đường ép dẹt thân mình như một dải ruy băng để lượn từ cây này sang cây khác.' },
  'flying-lizard': { name: 'Thằn lằn bay', kind: 'creature', fact: 'Thằn lằn bay giương đôi "cánh" là nếp da căng trên xương sườn để lượn giữa các thân cây.' },
  scorpion: { name: 'Bọ cạp', kind: 'creature', fact: 'Bọ cạp phát sáng xanh lục dưới ánh đèn tia cực tím, và đến nay các nhà khoa học vẫn chưa biết chắc vì sao.' },
  elephant: { name: 'Voi châu Á', kind: 'creature', fact: 'Voi là biểu tượng quốc gia của Thái Lan; ngày 13 tháng 3 hằng năm là Ngày Voi Thái.' },
  gibbon: { name: 'Vượn tay trắng', kind: 'creature', fact: 'Mỗi sáng, đôi vượn tay trắng "song ca" vang khắp rừng để giữ lãnh thổ của gia đình.' },
  'sun-bear': { name: 'Gấu chó', kind: 'creature', fact: 'Gấu chó là loài gấu nhỏ nhất thế giới; vệt lông vàng trên ngực mỗi con mang một hình dạng riêng.' },
  porcupine: { name: 'Nhím', kind: 'creature', fact: 'Nhím không bắn được lông: những chiếc lông nhọn chỉ rời ra và mắc vào kẻ thù khi chạm phải.' },
  'siamese-cat': { name: 'Mèo Xiêm', kind: 'creature', fact: 'Mèo Xiêm (Wichien Maat) có nguồn gốc từ Thái Lan và đã được tả trong tập thơ về mèo "Tamra Maew" thời Ayutthaya.' },
  duck: { name: 'Vịt cổ xanh', kind: 'creature', fact: 'Vịt cổ xanh là tổ tiên của hầu hết các giống vịt nhà trên thế giới.' },
  rooster: { name: 'Gà chọi Thái', kind: 'creature', fact: 'Truyền thuyết kể vua Naresuan của Ayutthaya có một chú gà chọi lừng danh, nên đền thờ ngài đầy tượng gà trống.' },
  peacock: { name: 'Công lục', kind: 'creature', fact: 'Công lục là loài công bản địa của Thái Lan, có chiếc mào dựng đứng như một chùm lông nhỏ.' },
  myna: { name: 'Sáo nâu', kind: 'creature', fact: 'Sáo nâu bắt chước được tiếng người và tiếng động quanh nhà; chúng là một trong những loài chim quen thuộc nhất ở phố thị Thái Lan.' },
  swallow: { name: 'Chim nhạn', kind: 'creature', fact: 'Mỗi mùa đông, chim nhạn bay hàng nghìn cây số từ phương Bắc về tránh rét ở Thái Lan.' },
  'rhino-beetle': { name: 'Bọ hung sừng', kind: 'creature', fact: 'Miền Bắc Thái Lan có trò chơi dân gian chọi bọ hung: hai chú bọ đực đấu sừng trên một khúc mía.' },
  cicada: { name: 'Ve sầu', kind: 'creature', fact: 'Chỉ ve sầu đực mới "hát": chúng rung một lớp màng ở bụng để tạo tiếng kêu vang khắp mùa hè.' },
  bee: { name: 'Ong mật', kind: 'creature', fact: 'Để làm ra một thìa mật nhỏ, cả đàn ong phải bay qua hàng nghìn bông hoa.' },
  'lantern-bug': { name: 'Bọ đèn mõm dài', kind: 'creature', fact: 'Bọ đèn có cái mõm dài màu đỏ; người xưa tưởng nó phát sáng nên đặt tên như chiếc đèn lồng.' },
  parakeet: { name: 'Vẹt ngực đỏ', kind: 'creature', fact: 'Vẹt ngực đỏ sống thành đàn ồn ào, làm tổ trong hốc cây và rất mê hạt, quả chín.' },
  // Đồ vật
  key: { name: 'Chìa khóa cổ', kind: 'object', fact: 'Chìa khóa cổ có phần răng được rèn thủ công, khớp với đúng một ổ khóa.' },
  compass: { name: 'La bàn', kind: 'object', fact: 'Kim la bàn luôn chỉ theo từ trường Trái Đất, dẫn đường cho thủy thủ suốt nhiều thế kỷ.' },
  letter: { name: 'Thư niêm sáp', kind: 'object', fact: 'Con dấu sáp từng dùng để niêm phong thư và chứng minh ai là người gửi.' },
  'pocket-watch': { name: 'Đồng hồ quả quýt', kind: 'object', fact: 'Đồng hồ bỏ túi rất phổ biến trước khi đồng hồ đeo tay thịnh hành vào đầu thế kỷ 20.' },
  quill: { name: 'Bút lông ngỗng', kind: 'object', fact: 'Bút lông ngỗng là cây bút viết phổ biến ở châu Âu suốt hơn một nghìn năm.' },
  teacup: { name: 'Tách trà Peranakan', kind: 'object', fact: 'Đồ sứ Peranakan (Nyonya ware) nổi bật với sắc hồng, xanh ngọc và họa tiết phượng hoàng.' },
  'coin-pouch': { name: 'Túi tiền xu', kind: 'object', fact: 'Thời thuộc địa, người Singapore tiêu "đô la eo biển" (Straits dollar).' },
  spyglass: { name: 'Ống nhòm viễn vọng', kind: 'object', fact: 'Kính viễn vọng khúc xạ ra đời ở Hà Lan vào đầu thế kỷ 17.' },
  vase: { name: 'Bình gốm men lam', kind: 'object', fact: 'Gốm men lam được vẽ hoa văn bằng màu cobalt rồi mới tráng men và nung.' },
  scroll: { name: 'Cuộn kinh cổ', kind: 'object', fact: 'Kinh sách thời xưa thường được chép tay trên những cuộn giấy dài.' },
  'magnifying-glass': { name: 'Kính lúp', kind: 'object', fact: 'Kính lúp trở thành "biểu tượng" của nghề thám tử nhờ những câu chuyện về Sherlock Holmes.' },
  'paper-crane': { name: 'Hạc giấy', kind: 'object', fact: 'Theo truyền thuyết Nhật Bản, ai gấp đủ 1.000 con hạc giấy sẽ được một điều ước.' },
  'paper-boat': { name: 'Thuyền giấy', kind: 'object', fact: 'Thuyền bumboat trên sông Singapore xưa được vẽ đôi mắt ở mũi để "nhìn đường" tránh hiểm nguy.' },
  durian: { name: 'Sầu riêng', kind: 'object', fact: 'Sầu riêng không được mang lên tàu điện MRT vì mùi quá nồng — còn nhà hát Esplanade thì có biệt danh "quả sầu riêng".' },
  'fortune-cat': { name: 'Mèo thần tài', kind: 'object', fact: 'Người ta tin mèo thần tài giơ tay phải để gọi tài lộc, giơ tay trái để mời khách.' },
  'red-envelope': { name: 'Bao lì xì', kind: 'object', fact: 'Bao lì xì (ang pow) màu đỏ tượng trưng cho may mắn, thường được tặng dịp Tết Nguyên Đán.' },
  tiffin: { name: 'Cà mèn tingkat', kind: 'object', fact: 'Cà mèn tingkat nhiều tầng từng là "hộp cơm" quen thuộc của các gia đình Peranakan.' },
  satay: { name: 'Xiên satay', kind: 'object', fact: 'Mỗi tối, một đoạn phố cạnh chợ Lau Pa Sat được đóng lại để thành "Phố Satay".' },
  kite: { name: 'Diều wau bulan', kind: 'object', fact: 'Wau bulan — diều "trăng khuyết" — là loại diều truyền thống nổi tiếng của người Mã Lai.' },
  'vintage-camera': { name: 'Máy ảnh cổ', kind: 'object', fact: 'Những chiếc máy ảnh đầu tiên cần tới vài phút phơi sáng để chụp một tấm hình.' },
  hourglass: { name: 'Đồng hồ cát', kind: 'object', fact: 'Đồng hồ cát từng được dùng trên tàu biển để đo thời gian và ước tính tốc độ.' },
  deerstalker: { name: 'Mũ thám tử', kind: 'object', fact: 'Chiếc mũ hai lưỡi trai gắn liền với Sherlock Holmes nhờ các bức tranh minh họa truyện.' },
  'conical-hat': { name: 'Nón lá', kind: 'object', fact: 'Chiếc nón lá truyền thống đan từ lá cọ vừa che mưa nắng vừa là nét duyên dáng của người Việt Nam.' },
  lantern: { name: 'Đèn lồng Hội An', kind: 'object', fact: 'Đèn lồng phố Hội được làm từ khung tre và lụa tơ tằm, thắp sáng lung linh sông Hoài vào những đêm rằm.' },
  cyclo: { name: 'Xích lô', kind: 'object', fact: 'Xích lô là phương tiện giao thông ba bánh độc đáo, đưa du khách thong thả ngắm nhìn phố phường cổ kính.' },
  'temple-bell': { name: 'Chuông chùa Thái', kind: 'object', fact: 'Ở Doi Suthep, khách hành hương gõ cả dãy chuông đồng để cầu may; chiếc lá bồ đề treo dưới chuông giúp gió làm chuông ngân.' },
  'naga-head': { name: 'Rắn thần Naga', kind: 'object', fact: 'Cầu thang 306 bậc lên chùa Doi Suthep có hai thân rắn thần Naga uốn lượn làm tay vịn.' },
  'khon-mask': { name: 'Mặt nạ Khon', kind: 'object', fact: 'Khon là múa mặt nạ cung đình kể sử thi Ramakien; năm 2018 UNESCO ghi danh Khon là di sản văn hóa phi vật thể.' },
  'spirit-house': { name: 'Miếu thần đất', kind: 'object', fact: 'Hầu như nhà nào ở Thái Lan cũng có một san phra phum, ngôi miếu nhỏ cho thần đất, được dâng hoa và nước mỗi ngày.' },
  'lotus-bud': { name: 'Búp sen dâng lễ', kind: 'object', fact: 'Người Thái khéo léo gấp cánh hoa sen thành những nếp nhọn xinh xắn trước khi dâng lên chùa.' },
  'longtail-boat': { name: 'Thuyền đuôi dài', kind: 'object', fact: 'Thuyền đuôi dài gắn động cơ trên một trục dài; mũi thuyền buộc vải màu để tạ ơn nữ thần thuyền Mae Ya Nang.' },
  'royal-barge': { name: 'Thuyền ngự Suphannahong', kind: 'object', fact: 'Thuyền ngự Suphannahong được chạm từ một thân gỗ tếch duy nhất, mũi thuyền là hình thiên nga thần.' },
  krathong: { name: 'Hoa đăng krathong', kind: 'object', fact: 'Đêm rằm tháng 12 theo lịch Thái, người ta thả krathong xuống sông để tạ ơn nữ thần sông nước.' },
  'sky-lantern': { name: 'Đèn trời khom loi', kind: 'object', fact: 'Trong lễ Yi Peng ở Chiang Mai, hàng nghìn chiếc đèn trời cùng bay lên, mang theo lời ước của mọi người.' },
  'clay-lamp': { name: 'Đèn dầu đất nung', kind: 'object', fact: 'Mùa Yi Peng, người Lanna thắp những chiếc đèn dầu đất nung nhỏ (prateep) quanh nhà và chùa.' },
  'jasmine-garland': { name: 'Vòng hoa nhài', kind: 'object', fact: 'Vòng hoa nhài phuang malai được treo ở miếu thờ, trong xe và trên mũi thuyền như lời cầu bình an.' },
  'paper-umbrella': { name: 'Ô giấy Bo Sang', kind: 'object', fact: 'Làng Bo Sang gần Chiang Mai nổi tiếng với ô giấy vẽ tay, và mỗi năm đều có một lễ hội ô riêng.' },
  'long-drum': { name: 'Trống dài Lanna', kind: 'object', fact: 'Trống klong yao dẫn đầu các đoàn rước miền Bắc Thái Lan; người đánh vừa đeo trống vừa nhảy múa.' },
  'tuk-tuk': { name: 'Xe tuk-tuk', kind: 'object', fact: 'Cái tên "tuk-tuk" bắt chước tiếng động cơ kêu tuk-tuk-tuk của chiếc xe ba bánh.' },
  'boxing-gloves': { name: 'Găng Muay Thái', kind: 'object', fact: 'Ngày 17 tháng 3 là Ngày Muay Thái, tưởng nhớ võ sĩ Nai Khanom Tom thời Ayutthaya.' },
  'mango-sticky-rice': { name: 'Xôi xoài', kind: 'object', fact: 'Xôi xoài rưới nước cốt dừa là món tráng miệng mùa hè của Thái Lan, ngon nhất khi xoài chín vàng vào tháng 4, tháng 5.' },
  coconut: { name: 'Dừa xiêm', kind: 'object', fact: 'Dừa xiêm mang tên cũ của Thái Lan, nước Xiêm; nước dừa non ngọt mát, thơm nhẹ.' },
  'thai-tea': { name: 'Trà sữa Thái', kind: 'object', fact: 'Trà sữa Thái (cha yen) pha từ trà đen đậm, sữa đặc và thật nhiều đá; ngoài phố hay được đựng trong túi buộc dây.' },
  mangosteen: { name: 'Măng cụt', kind: 'object', fact: 'Măng cụt được gọi là "nữ hoàng trái cây"; số cánh hoa nhỏ ở đáy quả bằng đúng số múi bên trong.' },
  'noodle-bowl': { name: 'Mì thuyền', kind: 'object', fact: 'Mì thuyền (kuay teow ruea) xưa được bán ngay trên ghe, nên bát thật nhỏ cho khỏi đổ khi thuyền dập dềnh.' },
  'mortar-pestle': { name: 'Cối giã som tam', kind: 'object', fact: 'Gỏi đu đủ som tam được giã trong cối đất nung, tiếng chày "pok pok" vang khắp các quầy hàng.' },
  abacus: { name: 'Bàn tính', kind: 'object', fact: 'Những tiệm vàng và hiệu thuốc lâu đời của người Hoa ở phố Yaowarat từng tính tiền bằng bàn tính gỗ.' },
  'palm-leaf-book': { name: 'Kinh lá buông', kind: 'object', fact: 'Chữ trên kinh lá buông (bai lan) được khắc bằng bút sắt nhọn, rồi xoa muội than cho nét chữ hiện lên.' },
  kratip: { name: 'Giỏ xôi tre', kind: 'object', fact: 'Người miền Bắc và Đông Bắc Thái Lan ăn xôi hằng ngày, đựng trong giỏ tre đan để xôi luôn mềm dẻo.' },
  'treasure-map': { name: 'Bản đồ cổ', kind: 'object', fact: 'Bản đồ châu Âu xưa vẽ Ayutthaya như một hòn đảo, vì kinh thành được ba con sông bao quanh.' },
};

export function isCreature(type?: SpriteType): boolean {
  return !!type && type !== 'seal' && BESTIARY[type].kind === 'creature';
}
