#!/usr/bin/env node
/**
 * Regenerates what the game derives from its sources, which stay the single source of truth for
 * the art and the sound design:
 *
 *  1. Sprite drawings — every <ObjectSprite> (tools/sprites) is server-rendered, then measured in
 *     Chromium with sprites.css, so each camouflage variant keeps exactly its colours.
 *     → app/src/generated/spriteArt.ts
 *  2. Sound effects — the Web Audio synth (app/src/platform/synth) is rendered offline to WAV for
 *     iOS/Android (the web build keeps synthesising live).
 *     → app/assets/sounds/*.wav + app/src/generated/sounds.ts
 *
 * Run from the repo root:  npm run generate   (needs `npm install` at the root: esbuild, react-dom,
 * playwright)
 */
import { createRequire } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const toolsRoot = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(toolsRoot, '..');
const appRoot = path.join(repoRoot, 'app');
const rootRequire = createRequire(path.join(repoRoot, 'package.json'));

const esbuild = rootRequire('esbuild');
const React = rootRequire('react');
const { renderToStaticMarkup } = rootRequire('react-dom/server');
const { chromium } = rootRequire('playwright');

const SPRITE_SRC = path.join(toolsRoot, 'sprites/ObjectSprite.tsx');
const SPRITE_CSS = path.join(toolsRoot, 'sprites/sprites.css');
const AUDIO_SRC = path.join(appRoot, 'src/platform/synth/synth.ts');
const VOICES_SRC = path.join(appRoot, 'src/platform/synth/voices.ts');

const ART_OUT = path.join(appRoot, 'src/generated/spriteArt.ts');
const SOUND_DIR = path.join(appRoot, 'assets/sounds');
const SOUND_MAP_OUT = path.join(appRoot, 'src/generated/sounds.ts');

// Phone speakers are much quieter than laptop ones: lift every sound by the same +6 dB
// (the mix between sounds is unchanged; the loudest peak stays well below clipping).
const PHONE_GAIN = 2;

const HEADER = `// AUTO-GENERATED by tools/generate-assets.mjs — do not edit by hand.\n`;

/* -------------------------------------------------------------------------- */
/*                              1. Sprite drawings                             */
/* -------------------------------------------------------------------------- */

function loadObjectSprite() {
  const out = esbuild.buildSync({
    entryPoints: [SPRITE_SRC],
    bundle: true,
    write: false,
    format: 'cjs',
    platform: 'node',
    jsx: 'automatic',
    external: ['react', 'react/jsx-runtime'],
    loader: { '.css': 'empty' },
  });
  const mod = { exports: {} };
  new Function('require', 'module', 'exports', out.outputFiles[0].text)(rootRequire, mod, mod.exports);
  return mod.exports.ObjectSprite;
}

function spriteTypes() {
  const src = fs.readFileSync(SPRITE_SRC, 'utf8');
  return [...src.matchAll(/^\s*case '([a-z-]+)':/gm)].map((m) => m[1]);
}

function renderMarkups() {
  const ObjectSprite = loadObjectSprite();
  const markups = {};
  for (const type of spriteTypes()) {
    const html = renderToStaticMarkup(React.createElement(ObjectSprite, { type }));
    const svg = html.match(/<svg[\s\S]*<\/svg>/);
    if (!svg) throw new Error(`No <svg> rendered for sprite "${type}"`);
    markups[type] = svg[0];
  }
  return markups;
}

// Variants measured in the browser. Each wraps the sprite the way SceneLayer does on the web.
// Sentinel colours stand in for the chameleon tint (sampled per object at runtime).
const CAMO_FILL = 'rgb(1, 2, 3)';
const CAMO_INK = 'rgb(4, 5, 6)';
const VARIANTS = [
  { key: 'base', layer: 'scene-layer', sprite: 'hidden-sprite camo-ink is-found' },
  { key: 'chameleon', layer: 'scene-layer', sprite: 'hidden-sprite camo-chameleon' },
  { key: 'invisible', layer: 'scene-layer', sprite: 'hidden-sprite camo-invisible in-loupe' },
  { key: 'glow', layer: 'scene-layer glow-layer', sprite: 'hidden-sprite camo-ink' },
  { key: 'glowChameleon', layer: 'scene-layer glow-layer', sprite: 'hidden-sprite camo-chameleon' },
];

/** Runs in Chromium: measures structure, geometry and the resolved paint of every shape. */
function measureInBrowser({ markups, variants, camoFill, camoInk }) {
  const host = document.getElementById('host');
  const SHAPES = 'path,circle,ellipse,rect,line,polygon,polyline';
  const r = (v) => Math.round(v * 1000) / 1000;
  const num = (el, a) => parseFloat(el.getAttribute(a) || '0');

  function toPath(el) {
    const tag = el.tagName.toLowerCase();
    if (tag === 'path') return el.getAttribute('d');
    if (tag === 'circle' || tag === 'ellipse') {
      const cx = num(el, 'cx');
      const cy = num(el, 'cy');
      const rx = tag === 'circle' ? num(el, 'r') : num(el, 'rx');
      const ry = tag === 'circle' ? num(el, 'r') : num(el, 'ry');
      return `M ${r(cx - rx)} ${r(cy)} A ${rx} ${ry} 0 1 0 ${r(cx + rx)} ${r(cy)} A ${rx} ${ry} 0 1 0 ${r(cx - rx)} ${r(cy)} Z`;
    }
    if (tag === 'rect') {
      const x = num(el, 'x');
      const y = num(el, 'y');
      const w = num(el, 'width');
      const h = num(el, 'height');
      let rx = el.hasAttribute('rx') ? num(el, 'rx') : el.hasAttribute('ry') ? num(el, 'ry') : 0;
      let ry = el.hasAttribute('ry') ? num(el, 'ry') : rx;
      rx = Math.min(rx, w / 2);
      ry = Math.min(ry, h / 2);
      if (!rx || !ry) return `M ${x} ${y} H ${r(x + w)} V ${r(y + h)} H ${x} Z`;
      return [
        `M ${r(x + rx)} ${y}`,
        `H ${r(x + w - rx)} A ${rx} ${ry} 0 0 1 ${r(x + w)} ${r(y + ry)}`,
        `V ${r(y + h - ry)} A ${rx} ${ry} 0 0 1 ${r(x + w - rx)} ${r(y + h)}`,
        `H ${r(x + rx)} A ${rx} ${ry} 0 0 1 ${x} ${r(y + h - ry)}`,
        `V ${r(y + ry)} A ${rx} ${ry} 0 0 1 ${r(x + rx)} ${y} Z`,
      ].join(' ');
    }
    if (tag === 'line') return `M ${num(el, 'x1')} ${num(el, 'y1')} L ${num(el, 'x2')} ${num(el, 'y2')}`;
    const pts = (el.getAttribute('points') || '')
      .trim()
      .split(/[\s,]+/)
      .map(Number);
    let d = '';
    for (let i = 0; i + 1 < pts.length; i += 2) d += `${i ? 'L' : 'M'} ${pts[i]} ${pts[i + 1]} `;
    return tag === 'polygon' ? `${d}Z` : d.trim();
  }

  function ownMatrix(el) {
    if (!el.hasAttribute('transform')) return undefined;
    const m = el.transform.baseVal.consolidate()?.matrix;
    return m ? [m.a, m.b, m.c, m.d, m.e, m.f].map(r) : undefined;
  }

  function anim(el) {
    const cls = el.classList;
    const bb = el.getBBox();
    const at = (fx, fy) => [r(bb.x + bb.width * fx), r(bb.y + bb.height * fy)];
    const list = [];
    if (cls.contains('eye')) list.push({ kind: 'blink', origin: at(0.5, 0.5) });
    if (cls.contains('wing')) list.push({ kind: 'wing', origin: [24, 24] });
    if (cls.contains('tail')) list.push({ kind: 'tail', origin: cls.contains('tail-cat') ? at(0.1, 0.9) : at(0, 1) });
    if (cls.contains('wave')) list.push({ kind: 'wave', origin: at(0.7, 0.95) });
    if (cls.contains('glow-spot')) list.push({ kind: 'glowSpot' });
    return list;
  }

  const css = (c) => (c === camoFill ? '$fill' : c === camoInk ? '$ink' : c);
  const result = {};
  const warnings = [];

  for (const [type, markup] of Object.entries(markups)) {
    const paints = {};
    let tree = null;
    for (const v of variants) {
      host.innerHTML =
        `<div class="${v.layer}"><div class="${v.sprite}" style="--camo-fill: ${camoFill}; --camo-ink: ${camoInk}; width: 48px; height: 48px; left: 0; top: 0; transform: none;">` +
        `<div class="hs-orient"><div class="hs-shy"><div class="object-sprite-container ${type}">${markup}</div></div></div></div></div>`;
      const svg = host.querySelector('svg');
      svg.setAttribute('width', '48');
      svg.setAttribute('height', '48');
      const leaves = [...svg.querySelectorAll(SHAPES)];
      paints[v.key] = leaves.map((el) => {
        const cs = getComputedStyle(el);
        return {
          fill: css(cs.fill),
          stroke: css(cs.stroke),
          visible: cs.visibility !== 'hidden',
          sw: parseFloat(cs.strokeWidth),
          cap: cs.strokeLinecap,
          join: cs.strokeLinejoin,
          dash: cs.strokeDasharray,
          opacity: parseFloat(cs.opacity),
        };
      });

      if (v.key === 'base') {
        let leaf = 0;
        const walk = (el) => {
          const tag = el.tagName.toLowerCase();
          const node = { m: ownMatrix(el), anim: anim(el) };
          if (node.anim.length && node.m) warnings.push(`${type}: animated <${tag}> has its own transform`);
          if (tag === 'g') return { ...node, kind: 'g', children: [...el.children].map(walk) };
          return { ...node, kind: 'shape', d: toPath(el), leaf: leaf++ };
        };
        tree = [...svg.children].map(walk);
      }
    }
    result[type] = { tree, paints };
  }

  // Container-level styles per variant, for the record (blend, filter, opacity)
  const containers = {};
  for (const v of variants) {
    host.innerHTML = `<div class="${v.layer}"><div class="${v.sprite}"><div class="hs-orient"><div class="hs-shy"><div class="object-sprite-container ${v.key === 'base' ? 'sprite-found' : ''}"><svg></svg></div></div></div></div></div>`;
    const s = getComputedStyle(host.querySelector('.hidden-sprite'));
    const c = getComputedStyle(host.querySelector('.object-sprite-container'));
    containers[v.key] = {
      sprite: { opacity: s.opacity, blend: s.mixBlendMode, filter: s.filter },
      container: { opacity: c.opacity, filter: c.filter },
    };
  }
  return { result, warnings, containers };
}

const LINECAP = { butt: undefined, round: 'round', square: 'square' };
const LINEJOIN = { miter: undefined, round: 'round', bevel: 'bevel' };

/** Compacts the browser measurements into the generated art table. */
function buildArt(measured) {
  const art = {};
  for (const [type, { tree, paints }] of Object.entries(measured)) {
    const base = paints.base;
    const shapes = base.map((p, i) => {
      for (const key of ['chameleon', 'invisible', 'glow', 'glowChameleon']) {
        const q = paints[key][i];
        if (q.sw !== p.sw || q.cap !== p.cap || q.join !== p.join || q.dash !== p.dash) {
          throw new Error(`${type}: variant "${key}" changes stroke geometry of shape ${i}`);
        }
      }
      const glow = paints.glow[i];
      const glowCh = paints.glowChameleon[i];
      if (glow.visible !== glowCh.visible) throw new Error(`${type}: glow visibility depends on camouflage (shape ${i})`);
      const dash =
        p.dash && p.dash !== 'none'
          ? p.dash
              .split(/[\s,]+/)
              .map((v) => parseFloat(v))
              .filter((v) => !Number.isNaN(v))
          : undefined;
      return {
        stroke: {
          width: p.sw,
          cap: LINECAP[p.cap],
          join: LINEJOIN[p.join],
          dash,
          opacity: p.opacity !== 1 ? p.opacity : undefined,
        },
        base: [p.fill, p.stroke],
        chameleon: [paints.chameleon[i].fill, paints.chameleon[i].stroke],
        invisible: [paints.invisible[i].fill, paints.invisible[i].stroke],
        glow: glow.visible ? [glow.fill, glow.stroke] : null,
        // The chameleon colour rules outrank a few glow rules on the web (e.g. firefly lanterns)
        glowChameleon: glowCh.visible ? [glowCh.fill, glowCh.stroke] : null,
      };
    });

    const strip = (node) => {
      const out = {};
      if (node.m) out.m = node.m;
      if (node.anim.length) out.anim = node.anim;
      if (node.kind === 'g') {
        out.children = node.children.map(strip);
      } else {
        const s = shapes[node.leaf];
        out.d = node.d;
        out.paint = {
          ...Object.fromEntries(Object.entries(s.stroke).filter(([, v]) => v !== undefined)),
          base: s.base,
          ...(same(s.chameleon, s.base) ? {} : { chameleon: s.chameleon }),
          ...(same(s.invisible, s.base) ? {} : { invisible: s.invisible }),
          glow: s.glow,
          ...(s.glow && s.glowChameleon && !same(s.glowChameleon, s.glow) ? { glowChameleon: s.glowChameleon } : {}),
        };
      }
      return out;
    };
    art[type] = tree.map(strip);
  }
  return art;
}

const same = (a, b) => a[0] === b[0] && a[1] === b[1];

/* -------------------------------------------------------------------------- */
/*                               2. Sound effects                              */
/* -------------------------------------------------------------------------- */

async function bundleSynth() {
  const exposeVoices = {
    name: 'expose-voices',
    setup(build) {
      // VOICE_OF is module-private in the synth; expose it to the generator only
      build.onLoad({ filter: /synth[\\/]voices\.ts$/ }, (args) => ({
        contents: `${fs.readFileSync(args.path, 'utf8')}\nexport { VOICE_OF };\n`,
        loader: 'ts',
      }));
    },
  };
  const out = await esbuild.build({
    stdin: {
      contents: `export { synth } from ${JSON.stringify(AUDIO_SRC.replace(/\\/g, '/'))};\nexport { VOICE_OF } from ${JSON.stringify(VOICES_SRC.replace(/\\/g, '/'))};\n`,
      resolveDir: repoRoot,
      loader: 'ts',
    },
    bundle: true,
    write: false,
    format: 'iife',
    globalName: 'Synth',
    platform: 'browser',
    plugins: [exposeVoices],
  });
  return out.outputFiles[0].text;
}

/** Runs in Chromium: renders one synth call into PCM samples with an OfflineAudioContext. */
async function renderInBrowser({ call, arg, seconds, sampleRate, gain }) {
  const { synth } = window.Synth;
  const ctx = new OfflineAudioContext(1, Math.ceil(sampleRate * seconds), sampleRate);
  // The synth builds its context lazily with `new AudioContext()`: hand it the offline one
  window.AudioContext = function () {
    return ctx;
  };
  ctx.resume = () => Promise.resolve();
  synth.ctx = null;
  synth.masterGain = null;
  synth.setSoundEnabled(true);
  synth[call](arg);
  const buffer = await ctx.startRendering();
  const data = buffer.getChannelData(0);
  // Trim the silent tail (keep any intentional lead-in, e.g. the voice waits for the chime)
  let end = data.length;
  while (end > 0 && Math.abs(data[end - 1]) < 1e-4) end--;
  end = Math.min(data.length, end + Math.round(sampleRate * 0.02));
  return Array.from(data.subarray(0, end), (v) => Math.round(Math.max(-1, Math.min(1, v * gain)) * 32767));
}

function wav(samples, sampleRate) {
  const bytes = samples.length * 2;
  const buf = Buffer.alloc(44 + bytes);
  buf.write('RIFF', 0);
  buf.writeUInt32LE(36 + bytes, 4);
  buf.write('WAVE', 8);
  buf.write('fmt ', 12);
  buf.writeUInt32LE(16, 16);
  buf.writeUInt16LE(1, 20); // PCM
  buf.writeUInt16LE(1, 22); // mono
  buf.writeUInt32LE(sampleRate, 24);
  buf.writeUInt32LE(sampleRate * 2, 28);
  buf.writeUInt16LE(2, 32);
  buf.writeUInt16LE(16, 34);
  buf.write('data', 36);
  buf.writeUInt32LE(bytes, 40);
  samples.forEach((s, i) => buf.writeInt16LE(s, 44 + i * 2));
  return buf;
}

/* -------------------------------------------------------------------------- */

async function main() {
  console.log('› Server-rendering sprites…');
  const markups = renderMarkups();
  console.log(`  ${Object.keys(markups).length} sprite types`);

  const chromePath = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
  const browser = await chromium.launch(fs.existsSync(chromePath) ? { executablePath: chromePath } : { channel: 'chrome' });
  try {
    const page = await browser.newPage();
    const spriteCss = fs.readFileSync(SPRITE_CSS, 'utf8');
    await page.setContent(
      `<!doctype html><html><head><style>${spriteCss}\n*{animation:none!important;transition:none!important}</style></head>` +
        `<body><div id="host" style="position:relative;width:48px;height:48px"></div></body></html>`
    );

    console.log('› Measuring camouflage variants in Chromium…');
    const { result, warnings, containers } = await page.evaluate(measureInBrowser, {
      markups,
      variants: VARIANTS,
      camoFill: CAMO_FILL,
      camoInk: CAMO_INK,
    });
    warnings.forEach((w) => console.warn(`  ! ${w}`));
    console.log('  container styles:', JSON.stringify(containers));

    const art = buildArt(result);
    const icons = Object.fromEntries(Object.entries(markups));
    fs.mkdirSync(path.dirname(ART_OUT), { recursive: true });
    fs.writeFileSync(
      ART_OUT,
      `${HEADER}import type { SpriteType } from '../core/model';\nimport type { SpriteArtNode } from '../board/scene/spriteArt';\n\n` +
        `/** Shape tree of every sprite (48×48 view box) with its paint in each camouflage variant. */\n` +
        `export const SPRITE_ART: Partial<Record<SpriteType, SpriteArtNode[]>> = ${JSON.stringify(art)};\n\n` +
        `/** The same drawings as SVG markup, for the static icons (quest cards, album). */\n` +
        `export const SPRITE_SVG: Partial<Record<SpriteType, string>> = ${JSON.stringify(icons)};\n`
    );
    console.log(`  wrote ${path.relative(appRoot, ART_OUT)} (${Math.round(fs.statSync(ART_OUT).size / 1024)} KB)`);

    console.log('› Rendering sound effects offline…');
    await page.addScriptTag({ content: await bundleSynth() });
    const voiceOf = await page.evaluate(() => window.Synth.VOICE_OF);
    const sampleRate = 44100;
    const jobs = [
      ...[1, 2, 3, 4, 5].map((combo) => ({ name: `found-${combo}`, call: 'playFound', arg: combo })),
      { name: 'wrong', call: 'playWrong' },
      { name: 'hint', call: 'playHint' },
      { name: 'page-turn', call: 'playPageTurn' },
      { name: 'fog', call: 'playFog' },
      { name: 'creature', call: 'playCreature' },
      { name: 'rustle', call: 'playRustle' },
      { name: 'victory', call: 'playVictory' },
    ];
    const voiceNames = [...new Set(Object.values(voiceOf))];
    for (const voice of voiceNames) {
      const type = Object.keys(voiceOf).find((t) => voiceOf[t] === voice);
      jobs.push({ name: `voice-${voice}`, call: 'playVoice', arg: type });
    }

    fs.rmSync(SOUND_DIR, { recursive: true, force: true });
    fs.mkdirSync(SOUND_DIR, { recursive: true });
    let total = 0;
    for (const job of jobs) {
      const samples = await page.evaluate(renderInBrowser, {
        call: job.call,
        arg: job.arg,
        seconds: 3,
        sampleRate,
        gain: PHONE_GAIN,
      });
      const file = wav(samples, sampleRate);
      total += file.length;
      fs.writeFileSync(path.join(SOUND_DIR, `${job.name}.wav`), file);
    }
    console.log(`  ${jobs.length} sounds, ${Math.round(total / 1024)} KB in ${path.relative(appRoot, SOUND_DIR)}`);

    const req = (name) => `require('../../assets/sounds/${name}.wav')`;
    const voices = Object.entries(voiceOf)
      .map(([type, voice]) => `  '${type}': ${req(`voice-${voice}`)},`)
      .join('\n');
    fs.mkdirSync(path.dirname(SOUND_MAP_OUT), { recursive: true });
    fs.writeFileSync(
      SOUND_MAP_OUT,
      `${HEADER}import type { SpriteType } from '../core/model';\n\n` +
        `/** Game sounds rendered from the web synth (index = combo - 1 for the chime). */\n` +
        `export const SFX = {\n` +
        `  found: [${[1, 2, 3, 4, 5].map((c) => req(`found-${c}`)).join(', ')}],\n` +
        `  wrong: ${req('wrong')},\n  hint: ${req('hint')},\n  pageTurn: ${req('page-turn')},\n  fog: ${req('fog')},\n` +
        `  creature: ${req('creature')},\n  rustle: ${req('rustle')},\n  victory: ${req('victory')},\n};\n\n` +
        `/** Each creature / object's own voice (already delayed to follow the chime). */\n` +
        `export const VOICES: Partial<Record<SpriteType, number>> = {\n${voices}\n};\n`
    );
    console.log(`  wrote ${path.relative(appRoot, SOUND_MAP_OUT)}`);
  } finally {
    await browser.close();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
